### ISSUE TITLE
[new] No LoTSS coverage crashes pipeline

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#14]
The pipeline crashes when there is no LoTSS coverage for the data. I tried https://github.com/lmorabit/long_baseline_pipeline/commit/39491737de1ecc34df9b85bde2f5774624440be5 (the latest) on 4C43.15 which isn't in the surveys pointings (yet), causing problems as `find_close_objs` is run directly after querying the catalogues.

For now I've tried changing

https://github.com/lmorabit/long_baseline_pipeline/blob/39491737de1ecc34df9b85bde2f5774624440be5/plugins/PipelineStep_DownloadCats.py#L290-L292

to

```python
lotss_catalogue = my_lotss_catalogue( MSname, Radius=lotss_radius, bright_limit_Jy=bright_limit_Jy ) 
lbcs_catalogue = my_lbcs_catalogue( MSname, Radius=lbcs_radius ) 
if len(lotss_catalogue) == 0:
	print('Target field not in LoTSS coverage yet! Only writing {:s}'.format(delay_cals_file))
	lbcs_catalogue.write(delay_cals_file, format='csv')
	return
result = find_close_objs( lotss_catalogue, lbcs_catalogue, tolerance=match_tolerance ) 
```

which seems to work for now (will see if it crashes later on perhaps, because of this).

**Comment by lmorabit** [comment]
Thanks! I've updated per your suggestion.  The pipeline at the moment doesn't use the LoTSS info yet, so it won't crash until we start doing wide-field.
