### ISSUE TITLE
[new] Parset variable order causes {{ job_directory }} to not be expanded

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#15]
I had to change the order of some variables in the parset, moving
https://github.com/lmorabit/long_baseline_pipeline/blob/39491737de1ecc34df9b85bde2f5774624440be5/long_baseline_pipeline.parset#L39-L43

below

https://github.com/lmorabit/long_baseline_pipeline/blob/39491737de1ecc34df9b85bde2f5774624440be5/long_baseline_pipeline.parset#L46

or {{ job_directory }} wouldn't properly expand for the catalogues.

**Comment by lmorabit** [comment]
This has been fixed in the new branch, and doesn't look to be a problem in the master.
