### ISSUE TITLE
getting the eht imager working for lofar data

### ISSUE THREAD

**Issue by lmorabit** [lmorabit/long_baseline_pipeline#2]
I'm opening this issue for those of us testing the eht imager. So far I've tried testing it on two types of data:

1) a single subband of a calibrator source (3C 48) which has already been through NDPPP once to get the amplitudes on approximately the right scale
![3c48_comparison](https://user-images.githubusercontent.com/7126374/38820377-9e71adc2-4195-11e8-8500-5ef0bcbf302e.png)

2) the full bandwidth (but heavily averaged, post delay calibration) of an in-field calibrator source which is about 1.95 Jy

What I've learned so far:
- using cphase and camp separately gives slightly better results than using 'bs' mode
- flagging is important. If you have catastrophic outliers this will give you chi^2 values of several million and the fitting won't go anywhere
- if the prior is too big, you can end up pushing flux into the first sidelobes of the psf, which drives the model in completely the wrong direction
- the convergence critieria will be important for any automated pipeline -- at the moment, I can see where the model becomes good and then it keeps going to the max niter and becomes worse

all of this has been accomplished with https://github.com/lmorabit/long_baseline_pipeline/blob/master/eht_imager_scripts/eht_imaging.py

it's also possible to use another image as a prior, e.g. download something from the VLA imaging archive, but in this case I found that if imaging was done with AIPS the eht imager doesn't find the beam parameters so there's also a script https://github.com/lmorabit/long_baseline_pipeline/blob/master/eht_imager_scripts/update_fits_with_beam_parameters.py to fix that

**Comment by lmorabit** [comment]
After properly flagging the data, I'm getting much better results. I think this is in part because the amplitudes don't have giant outliers, but also because the clipfloor is working -- I think this is an absolute value, so it will need to be calculated by the script.  The script also needs to do a better job of calculating the zero baseline flux -- it's coming out about a factor of 2 higher than what I see from the amplitude vs. u-v plot.  I think the clipfloor value will be critical for avoiding pushing model components into LOFAR sidelobes.

1st iteration from a single gaussian prior:
![1stiter](https://user-images.githubusercontent.com/7126374/39198601-5ca09214-47df-11e8-849b-f123181978e0.png)

2nd interation from the model made from the 1st iteration:
![2nditer](https://user-images.githubusercontent.com/7126374/39198635-6ee06b20-47df-11e8-90f7-4b5a811f217f.png)

with the convergence criteria set to 0.0005 and clipfloor set to 0.001, the first run converged after 12 steps, and the second run converged after 22 steps.

This was using only DE601, DE602, DE604, DE605

**Comment by lmorabit** [comment]
the final image from the second loop looks like what i expect for this source, by the way.

**Comment by lmorabit** [comment]
I tried another source in the field with the same parameters.  I'm not sure if I should be worried that it's finding similar structure (top row is one source, bottom row is another source; left column is the model and right column is the model convolved to the beam):

![comparison](https://user-images.githubusercontent.com/7126374/39258062-eb3790e2-48aa-11e8-95cc-3debb54c002c.png)

Thoughts? comments?  I think I will try changing the clipfloor now that I have nice data and a handle on how things work.

Still finding for the other source that the maximum amp value I'm calculating is a factor of about 2 larger than it should be. I'm calculating this using taql to find the mean absolute value of the DATA on the shortest baseline (DE601 -- DE605).

**Comment by twshimwell** [comment]
Perhaps worth trying a few more sources?

**Comment by lmorabit** [comment]
processing more now, will probably take a couple days.

**Comment by nealjackson** [comment]
Hi Leah

I added a modified version of eht_imaging.py, called eht_imaging_new.py, to my github, nealjackson/lofar-lb .

The main change is that it contains an option --use_first . This will interrogate the FIRST catalogue to try and get a prior.

It also doesn't require DE601 and DE605 to be present; if they aren't it will use the first baseline from the ctels.

For testing I removed the clipfloor argument as this caused it to crash for me (I think it was something to do with the overall amplitude scales).

cheers
Neal.

________________________________

**Comment by lmorabit** [comment]
Notes from a conversation with A. Chael on the EHT imager
1) set clipfloor to about 1 - 5%  of the peak flux in the image
2) zero baseline flux -- use external values or estimate from shortest baseline
3) uniform weighting option can lower the sensitivity to outliers -- but flagging it before is good
4) yes they also find that outliers can cause issues
5) Not particularly sensitive to initial number of pixels -- 64 is probably a good number -- but can converge more quickly if step up the npix through iterations
6) don't use a gaussian prior with a FWHM larger than half the field of view -- larger gaussians require larger field of views -- or put in a top hat that zeros out the flux. 
7) convergence criteria
-- there is a obs.chisquared image function to get the chi-squared
-- variety of plotting stufff 
8) obsdata can be told if it is given calibrated or uncalibrated data, but this option isn't used at the moment
9) closure phase and amplitude usually better than bispectrum -- but sometimes bispectrum can help if you get stuck in a local minimum on the closure phase/amp surface
10) s1/s2 can be optimised as well, maybe try this.

**Comment by lmorabit** [comment]
It has been over a year since we used the EHT imager. I am closing this issue.
