### ISSUE TITLE
Loop 3 number of antennas mismatched

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#20]
Loop 3 crashes, giving the following error:

```
File "/data020/scratch/sean/run1/git/long_baseline_pipeline/bin/loop3B_v1.py", line 78, in selfcal
coh[i] = loop3_service.coherence_metric (outcal)
ValueError: could not broadcast input array from shape (63) into shape (74)
```

The reason for this is that `len(coh[i])` is 74 but the right hand side has 63 elements. The `len(coh[i])` is defined by the MS antenna table:

```
import casacore.tables
ms, antennas = 'test.ms', []
for antenna in casacore.tables.table(ms + '/ANTENNA').select('NAME'):
    antennas.append(antenna)
print(len(antennas))  # 74
``` 

However, in `loop3_service.coherence_metric`, the number of antennas is taken from the H5parm:

https://github.com/lmorabit/long_baseline_pipeline/blob/7610d53f209b389bf03e6949508259dccb51280c/bin/loop3_serviceB.py#L144

Here, `len(ant)` is 63 because this excludes antennas for which 100% of data have been flagged for some stations (during Prefactor).

I'll write a fix for this later in the week. I'm documenting it here for future reference. This is before phasing the stations up. After using an NDPPP filter step, with `filter.remove = True`, antennas not used are removed. This solves the issue. Since loop 3 will be used after this has been done, it shouldn't be an issue for the pipeline.

**Comment by lmorabit** [comment]
Which antennas were 100% flagged?

**Comment by mooneyse** [comment]
RS208 and PL610 which I flagged in Prefactor.

Also RS406, RS407, RS508, DE601, DE602, DE603, DE604, UK608, and DE609 are also not there. I assume they were flagged by Prefactor but I can check it out more. Maybe some weren't operational during the observation. They aren't shown in the Prefactor inspection plots either.

![image](https://user-images.githubusercontent.com/20988307/53448790-2966c700-3a10-11e9-9bb0-72437f10274e.png)

**Comment by lmorabit** [comment]
They were already not there in the prefactor calibrator pipeline?

**Comment by mooneyse** [comment]
Sorry, forgot about this. Basically the issue won't occur when loop 3 is run in the context of the LB pipeline as ST001 will already be formed and an NDPPP filter step will have been done, so I'll close it.
