### ISSUE TITLE
VOtable conversion problem in download_cats

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#21]
For me
https://github.com/lmorabit/long_baseline_pipeline/blob/51f2c3c49d1e350c9210bb32ddc546e53f48168d/plugins/PipelineStep_DownloadCats.py#L94
in lines 94 and 133 fail. I had to change them to just `t.to_table()`. This mis probably just a PyVO version difference.

**Comment by lmorabit** [comment]
fix was merged.
