### ISSUE TITLE
do_parallel crashes with a single calibrator source

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#25]
**The pipeline crash**
The `do_parallel` step, which calls `long_baseline_pipeline/bin/evaluate_potential_delay_calibrators.py`, crashes:
```
ERROR   node.lof020.control.lofar.python_plugin: sequence item 2: expected string, Column found
```
`delay_calibrators.csv` looks like this:
```
'LOTSS_RA','LOTSS_DEC','Source_id','Total_flux'
187.277915,2.052388,cal1,9.8
```
I ran it outside the pipeline and it threw this error:
```
Traceback (most recent call last):
  File "./evaluate_potential_delay_calibrators.py", line 314, in <module>
    main( MS_input, args.lotss_file, ncpu=args.ncpu, datacol=args.datacol, nsbs=args.nsbs )
  File "./evaluate_potential_delay_calibrators.py", line 294, in main
    coords = lotss2coords( lotss_file )
  File "./evaluate_potential_delay_calibrators.py", line 238, in lotss2coords
    a = ','.join([str(a['LOTSS_RA']),str(a['LOTSS_DEC']),a['Source_id']])
TypeError: sequence item 2: expected string, Column found
```
---
**The fix**
This line has to change:
https://github.com/lmorabit/long_baseline_pipeline/blob/ac54f61c85466d016be60595d052e0d28bc63639/bin/evaluate_potential_delay_calibrators.py#L238
It should be this:
```python
src = a['Source_id']
if type(src) != str:
    src = 'S' + str(src)
    a = ','.join([str(a['LOTSS_RA']), a(tmp['LOTSS_DEC']), src])
```
This is already done for the case where there is more than one source in `delay_calibrators.csv`.

**Comment by lmorabit** [comment]
Thanks, I've made these changes!

**Comment by tikk3r** [comment]
Something to keep in mind is that Python2 has two string types: `str` and `unicode` which are both an instance of `basestring`. This has been an inssue in prefactor a couple of times, so to be safe check against both or check if it's an instance of `basestring`:
```python
try:
    basestring
except NameError:
    # Python3, basestring is not longer there.
    basestring = str
if not isinstance(src, basestring):
    src = 'S' + str(src)
    a = ','.join([str(a['LOTSS_RA']), a(tmp['LOTSS_DEC']), src])
```

**Comment by lmorabit** [comment]
Fixed per Frits's suggestion.
