### ISSUE TITLE
library error in delay_cal_aoflag

### ISSUE THREAD

**Issue by DeepikaVenkattu** [lmorabit/long_baseline_pipeline#26]
Hi,
I'm running the lb pipeline on the Herts cluster and I've run into a cannot open shared object file error in the delay_cal_aoflag step - it can't find libgtkmm-3.0.so.1.  It's on /usr/lib64 in the LD_LIBRARY_PATH and the log file shows this path. Any suggestions would be much appreciated!
Thanks,
Deepika

**Comment by lmorabit** [comment]
Hi Deepika, this sounds like a setup problem rather than a pipeline problem, so I'm closing this issue but I'll contact you about it privately.
