### ISSUE TITLE
Open subtables with :: instead of /

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#28]
For example, in loop3:
https://github.com/lmorabit/long_baseline_pipeline/blob/407813eb5b481f0a354c6b143fba3e928cb34ac6/bin/loop3B_v1.py#L714
Opening a subtable with `/` is not reliable, as mentioned in the TaQL note. `::` shoud be used instead, i.e. instead of
```python
vis + '/SPECTRAL_WINDOW'
```
open it with
```python
vis + '::SPECTRAL_WINDOW'
```

This should fix e.g. the case where loop3 crashes with

    RuntimeError: Table <something>/SPECTRAL_WINDOW does not exist

**Comment by lmorabit** [comment]
I changed this in the newest version of the script (updated by Neal).
