### ISSUE TITLE
gains_toCS_h5parm.py does not handle missing pol axis

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#31]
A polarization axis is assumed to exist currently for amplitude or phase tables. Solving for e.g. `scalarphase` results in phase solutions without a polarization axis, crashing the copy script.

**Comment by lmorabit** [comment]
This can be updated, but it is low priority given the fact that the pipeline does not currently calculate scalarphase and this should not exist in the pipeline-generated h5parms.
