### ISSUE TITLE
The LBCS VO

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#34]
Hi, just following on from the chat on Slack - while the LBCS VO isn't up to date, I have a short script that looks up the LBCS webpage and writes a delay catalogue for sources around a given position like this for the LB pipeline:

```
Source_id,LOTSS_RA,LOTSS_DEC,Separation_deg,Goodness
L618324,133.703625,20.108528,0.0,PPPPPPPXPPXX-
L618058,133.305833,19.514722,0.7019,PPPPPPPXPPXX-
L618344,134.238375,21.195639,1.1967,PPPPPPPXPPXX-
```

I know the VO will be updated sometime so it eventually won't matter, but if this script has any value for the pipeline, let me know and I can make it pipeline-friendly. (If not, no hassle, this issue can be closed.) It's linked below in its current form, but would need some tweaks (Python 3 to 2, read the pointing centre from an MS, and making the script a plugin).

https://github.com/mooneyse/scripts/blob/master/find_best_lbcs.py

**Comment by lmorabit** [comment]
This is really great!  But It should be an obsolete issue when the VO is updated.  Could you post a link to this script on Slack please?

**Comment by mooneyse** [comment]
Yup I agree, cool :+1:
