### ISSUE TITLE
Bug (?) in copyST_gains step

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#5]
Plotting amplitude against time for the core stations, from the in-field calibrator's instrument table (after the `copyST_gains` step) gives a strange result. The amplitudes for the core stations look quite different from the ST001 amplitudes.
I did not run AOFlagger on the data before the pipeline (re-running it now to see if that makes a difference), but the overall calibration seems ok and since it copies solutions it should not affect anything, right? Running the flagger afterwards flags a large fraction of the data, but produces a decent image so at least the phases are alright.
Here's what I get from parmdbplot (same reference antenna for both):

**ST001:**
![st001_gain00](https://user-images.githubusercontent.com/2464769/40729539-e278fe94-642c-11e8-9c18-01c34d4ee724.png)

**Core Stations:** (this is CS006HBA0)
![cs006hba0_gain00](https://user-images.githubusercontent.com/2464769/40729647-1b9ced70-642d-11e8-950f-a742306d9906.png)

**Comment by lmorabit** [comment]
what reference antenna are you using?

**Comment by tikk3r** [comment]
> what reference antenna are you using?

For these plots the reference is RS305, but the pattern stays the same with different reference antennas.

**Comment by lmorabit** [comment]
and this is all from the same parmdb?

**Comment by tikk3r** [comment]
They are both from the same parmdb yes, plotted from `instrument` in `<LBCS calibrator>_L427100_SB000_uv.dppp_127A41D74t_143MHz.msdpppconcat`.

**Comment by lmorabit** [comment]
and the measurement set does not contain the CS stations, correct?

**Comment by lmorabit** [comment]
also -- just double checking -- this is *after* copyST_gains has been fixed to use addValues rather than addValuesGrid? If you re-ran on an instrument table that you'd already tried to manipulate there could be an issue.

**Comment by tikk3r** [comment]
Correct, that measurement set does not contain CS stations. This is indeed also after the fix to use `addValues` instead of `addValuesGrid`.

**Comment by lmorabit** [comment]
Rather than using parmdbplot.py, can you try the following just to double check it's not a plotting issue:

import lofar.parmdb as lp

cal_table = '<LBCS calibrator>_L427100_SB000_uv.dppp_127A41D74t_143MHz.msdpppconcat/instrument'

myparmdb = lp.parmdb( cal_table )

st00_real = myparmdb.getValues('Gain:0:0:Real:ST001')
cs6hb0_00_real = myparmdb.getValues('Gain:0:0:Real:CS006HBA0')

st_vals = st00_real['Gain:0:0:Real:ST001']['values']
cs_vals = s6hb0_00_real['Gain:0:0:Real:CS006HBA0']['values']

st_vals - cs_vals

**Comment by lmorabit** [comment]
Aha, I think I found the culprit! Only solutions for 'Gain:0:0:Real' are written for each CS station.  I'll update the script to write the Imag gains as well as the 1:1 gains.

**Comment by tikk3r** [comment]
> Aha, I think I found the culprit! Only solutions for 'Gain:0:0:Real' are written for each CS station. I'll update the script to write the Imag gains as well as the 1:1 gains.

Nice, hopefully that fixes it all. Checking in Python the real parts are the same, they pass `numpy.testing.assert_equal`, but indeed the Imag part is missing from the core station.

**Comment by lmorabit** [comment]
I've pushed the updated version of the script now.  Thanks for catching this!!
