### ISSUE TITLE
Convert tabs to spaces in loop3B_v1.py

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#53]
In `loop3B_v1.py`, there are tabs thoughout and it was written with a tab being 8 spaces. Many text editors interpret a tab as 4 spaces which messes up the indentation.

e.g. The image below. If I open and save the script in nano/Gedit/Atom the tabs are converted to 4 spaces and it fails when I run it.

![image](https://user-images.githubusercontent.com/20988307/68312581-2e097200-00ab-11ea-8866-6427ed112d24.png)

To remove the ambiguity maybe next week one of us can convert all tabs to 8 spaces. It is fairly trivial but useful imo.

Also, separate issue really but it is small: `montage` isn't installed in the Singularity image so I comment it out every time, otherwise I get errors like this:
```
montage -tile 6x0 -geometry 600x600 direction_133.305_19.515.MS_A_output.png
sh: montage: command not found
```

Given that it isn't a standard package and it isn't essential to the functioning of loop 3, I suggest adding a flag to the `make_montage` function to optionally skip this plotting step. e.g. changing
```python
def montage_plot( filepattern, imscale=0.65, nup='4x2', plot_resid=True):
    if filepattern.split('.')[-1] == 'fits':
```
to something like
```python
def montage_plot( filepattern, imscale=0.65, nup='4x2', plot_resid=True, dontplot=False):
    if dontplot:
        print('Skipping the montage plotting.')
        return
    if filepattern.split('.')[-1] == 'fits':
```
But it's no big deal either way, just a suggestion.

**Comment by tikk3r** [comment]
Better make it 4 spaces then, to comply with PEP-8.

`reindent` should take care of this swiftly.

**Comment by lmorabit** [comment]
pull request merged.
