### ISSUE TITLE
Behaviour of do_download option in DownloadCats step

### ISSUE THREAD

**Issue by jcroston** [lmorabit/long_baseline_pipeline#56]
If do_download is set to False in LB-Delay-Calibration.parset, then the DownloadCats step does not write any output delay_cat, subtract_cat and image_cat csv files. I'm unsure if there is a set of circumstances in which this is a useful option. It would seem intuitive that do_download should be set to False in a situation where both the lotss catalogue and the lbcs catalogue are already on disk rather than needing to be downloaded from the VO (e.g. because the data is from a bit of sky not in DR1, and calibrators from a bit of LBCS not yet on the VO). But actually at the moment do_download needs to be set to true in that situation, otherwise the catalogues needed for the LB-Split-Calibrators step are not written.

If there is an intended scenario where users don't want the catalogues written out then it might be useful to rename the do_download option to (e.g.) do_make_cats or similar, and/or make sure the various options around input and output from the Download_Cats step are explained in the documentation.

If users will always want the csv catalogues written out, then the do_download parameter is unnecessary, since if do_download is set to True, DownloadCats decides whether or not to download from the VO depending on whether the files already exist on disk, which works fine.

**Comment by lmorabit** [comment]
You're right, it's now pointless.  It is a parameter that was carried over before the script checked for the existence of files to determine whether or not to download.  The plugin and parset have been updated, and I will close this issue once tested.

**Comment by lmorabit** [comment]
tested.
