### ISSUE TITLE
Beam effects on LBCS calibrators

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#57]
Currently the split out infield calibrator(s) do not seem to be corrected for being away from the phase center further down the primary beam. This could cause beam effects to be absorbed in the amplitude solutions obtained with selfcal, more so for the ones further away, which can then no longer be transferred across the field.

**Comment by lmorabit** [comment]
Fixed with commit c053ff21c48e9b5245e2451f18a4889388be1c79 for Delay-Calibration.parset .  I'll leave this open until it's added to Split-Directions.parset.

**Comment by lmorabit** [comment]
fixed with commit be542ea9c2f34d43fb9e4d4ca8661fed8b7cf3e9
