### ISSUE TITLE
DownloadCats bug in call to my_lbcs_catalogue

### ISSUE THREAD

**Issue by jcroston** [lmorabit/long_baseline_pipeline#58]
The recent update to the DownloadCats plugin seems to have introduced a bug in the call to my_lbcs_catalogue (line 310). This looks like a copy of the call to my_lotss_catalogue, whereas it shouldn't have the bright_limit_Jy argument, and the outfile should be lbcs_catalogue, not lotss_catalogue. Fix coming shortly I hope.

**Comment by jcroston** [comment]
Possibly unnecessarily cumbersome for me to attempt to upload fix. All that needs changing is for line 310 to be:
    lbcs_catalogue = my_lbcs_catalogue( MSname, Radius=lotss_radius, outfile=lbcs_catalogue)

_(Ignore - github newbie, but worked it out now!)_

**Comment by lmorabit** [comment]
issue has been fixed!
