### ISSUE TITLE
substeps missing in apply_ddf?

### ISSUE THREAD

**Issue by jcroston** [lmorabit/long_baseline_pipeline#60]
It looks to me like the substeps "h5imp_ddf_map" and "h5imp_ddf" are missing from the apply_ddf list of steps (at least, fixing this stops it crashing for me!) My current pull request updates this too.

**Comment by lmorabit** [comment]
Yes -- I'm still updating the parset.  I have run into some software issues on the cluster this week and haven't gotten as far as I expected.  I'll email the long baseline list when it's done (and merge new into master then).

**Comment by jcroston** [comment]
Thanks - will stop meddling for now then!

**Comment by lmorabit** [comment]
steps have been added to apply_ddf list.
