### ISSUE TITLE
filter_baselines not defined

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#62]
The pipeline crashes with this error.

```
2020-01-20 08:50:05 WARNING node.LOFAR.executable_args.L751472_SB227_uv.MS: /opt/lofar/lofar/bin/NDPPP stderr:
std exception detected: Antenna Expression: Parse error at or near '{'
(near char. 0 in string "{{ filter_baselines }}")
```

`filter_baselines` isn't defined in `LB-Delay-Calibration.parset` but appears in the `filter` step.

https://github.com/lmorabit/long_baseline_pipeline/blob/afd3df8ecb26b72bf96c35f65a58b55ce47aa7d3/LB-Delay-Calibration.parset#L208

I removed it from my run for now but it should be defined or the correct parameter put in its place.

**Comment by lmorabit** [comment]
fixed with commit f619a2c
