### ISSUE TITLE
RA_LOTSS or LOTSS_RA?

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#63]
`skynet.py` expects `'RA_LOTSS'` in the delay catalogue. However, `parallel_split.py` expects `'LOTSS_RA'` (and likewise for declination).

https://github.com/lmorabit/long_baseline_pipeline/blob/afd3df8ecb26b72bf96c35f65a58b55ce47aa7d3/bin/parallel_split.py#L101

I won't change either as I'm not sure which is the desired label, so I'm just flagging it for others.

**Comment by lmorabit** [comment]
parallel_split.py is no longer used on the master branch -- do you need this updated still?

**Comment by mooneyse** [comment]
Nope, thanks :+1:
