### ISSUE TITLE
Minor issue with the plugin PipelineStep_DownloadCats.py

### ISSUE THREAD

**Issue by marcoiacobelli77** [lmorabit/long_baseline_pipeline#65]
Currently there is a mismatch with the name of the argument --continue_no_lotss: in the main function (line 297) the variable is named fail_lotss_ok = kwargs['continue_no_lotss'].lower().capitalize() instead of continue_without_lotss as expected in lines 319. As a consequence the plugin (and the pipeline) can fail, but a simple renaming of the variable can fix it.

**Comment by lmorabit** [comment]
fixed with commit 63c8a51
