### ISSUE TITLE
Channel range limitations in difmap

### ISSUE THREAD

**Issue by nealjackson** [lmorabit/long_baseline_pipeline#69]
If there are bad channels, difmap copes with this by a select command e.g. select I,1,3,5,10 takes channels 1-10 except channel 4 using two ranges. If there are more than 19 ranges, an error will be generated because difmap has a hard limit (see chlist.c and chlist.h in the difmap software tree). There are two possible solutions: (i) make a second change in the difmap software tree (in addition to the change in corplt.c), or (ii) modify selfcal_difmap.py to only allow the first 19 ranges. Both are hopefully straightforward changes, but we should discuss which approach is better.

**Comment by lmorabit** [comment]
With commit 8c4f17962f559f6c7ce4c57931c0b62c3979682d the selfcal script now takes only the first 19 channel ranges and prints a warning. Once we modify difmap and it's included in the singularity image, this can be removed. I'll leave the issue open until then.

**Comment by lmorabit** [comment]
No longer using difmap.
