### ISSUE TITLE
h5imp_ddf wrong output h5parm

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#70]
After converting the DDF solutions to H5parm format the concatenation at the `h5imp_ddf` appears to go wrong. The concatenated `ddf_solutions.h5` has a wrong and strange internal structure (checked plotting with both h5plot and LoSoTo for sanity). Each time slot contains a subset of frequency slots.

Inspecting the individual bands shows there are valid solutions there, so the concatenate must be getting confused somehow. It's probably something in losoto, as that's what's called, but I'm raising it here as well so people are aware.

The plots below show the strange transition between two adjacent timeslots and that e.g. time slot 2 contains normal valid solutions in the missing frequency spans.

| Time slot 2| Time slot 3|
:-: | :-:
![CS301_HBA1_concatenated_ddf_solutions](https://user-images.githubusercontent.com/2464769/96878474-32c16480-147b-11eb-8a81-3ac8e5bfa592.png) | ![CS301_HBA1_concatenated_ddf_solutions2](https://user-images.githubusercontent.com/2464769/96879040-d6127980-147b-11eb-8a38-d55815f99506.png)

150 MHz block timeslot 2 | 164 MHz block timeslot 2
:-: | :-:
![CS301_HBA1_150MHz_ddf_solutions](https://user-images.githubusercontent.com/2464769/96878469-3228ce00-147b-11eb-8149-0c1969272a89.png) | ![CS301_HBA1_164MHz_ddf_solutions](https://user-images.githubusercontent.com/2464769/96878782-83d15880-147b-11eb-9ad0-1a9fb2b13260.png)

**Comment by tikk3r** [comment]
Right, it's the unequally sized time/freq axes between the h5parms that it doesn't like.

**Comment by lmorabit** [comment]
so is this being fixed in losoto? or does it need a fix here?

**Comment by tikk3r** [comment]
I have changed the parset to apply the h5parms to the blocks individually instead of merging them into one. I'm testing that now.

**Comment by tikk3r** [comment]
To avoid the merge I changed the bit of
```
# add the international stations
addIS.control.type                  = pythonplugin
addIS.control.executable            = {{ lofar_vlbi_dir }}/bin/addIS_to_h5.py
addIS.control.max_per_node          = {{ num_proc_per_node }}
addIS.control.mapfiles_in           = [expand_concat_map.output.mapfile,ddf_h5parms.output.mapfile]
addIS.control.inputkeys             = [msin,h5parms]
addIS.argument.solset_in            = sol000
addIS.argument.solset_out           = sol001
addIS.argument.do_int_stations      = True
addIS.argument.flags                = [h5parms,msin]

# generate a mapfile with all files in a single entry
h5imp_ddf_map.control.kind              =   plugin
h5imp_ddf_map.control.type              =   compressMapfile
h5imp_ddf_map.control.mapfile_in        =   ddf_h5parms.output.mapfile
h5imp_ddf_map.control.mapfile_dir       =   input.output.mapfile_dir
h5imp_ddf_map.control.filename          =   h5imp_ddf_map

# collect all instrument tables into one h5parm
h5imp_ddf.control.kind                  =   recipe
h5imp_ddf.control.type                  =   executable_args
h5imp_ddf.control.executable            =   {{ losoto_directory }}/bin/H5parm_collector.py
h5imp_ddf.control.error_tolerance       =   {{ error_tolerance }}
h5imp_ddf.control.mapfile_in            =   h5imp_ddf_map.output.mapfile
h5imp_ddf.control.inputkey              =   h5parm
h5imp_ddf.argument.flags                =   [-v,-c,h5parm]
h5imp_ddf.argument.outh5parm            =   {{ job_directory }}/ddf_solutions.h5
h5imp_ddf.argument.insolset             =   sol001

# apply the solutions
ndppp_applycal.control.type                    = dppp
ndppp_applycal.control.max_per_node            = {{ num_proc_per_node_limit }}
ndppp_applycal.control.error_tolerance         = {{ error_tolerance }}
ndppp_applycal.control.mapfile_in              = dpppconcat.output.mapfile
ndppp_applycal.control.inputkey                = msfiles
ndppp_applycal.control.inplace                 = True
ndppp_applycal.argument.numthreads             = {{ max_dppp_threads }}
ndppp_applycal.argument.msin                   = msfiles
ndppp_applycal.argument.msin.datacolumn        = DATA
ndppp_applycal.argument.msout.datacolumn       = {{ delaycal_col }}
ndppp_applycal.argument.msout.writefullresflag = False
ndppp_applycal.argument.msout.storagemanager   = dysco
ndppp_applycal.argument.steps                  = [applyddf]
ndppp_applycal.argument.applyddf.type           = applycal
ndppp_applycal.argument.applyddf.parmdb         = {{ job_directory }}/ddf_solutions.h5
ndppp_applycal.argument.applyddf.correction     = fulljones
ndppp_applycal.argument.applyddf.solset         = sol000
ndppp_applycal.argument.applyddf.soltab         = [amplitude000,phase000]
```
to
```
# add the international stations
addIS.control.type                  = pythonplugin
addIS.control.executable            = {{ lofar_vlbi_dir }}/bin/addIS_to_h5.py
addIS.control.max_per_node          = {{ num_proc_per_node }}
addIS.control.mapfiles_in           = [expand_concat_map.output.mapfile,ddf_h5parms.output.mapfile]
addIS.control.inputkeys             = [msin,h5parms]
addIS.argument.solset_in            = sol000
addIS.argument.solset_out           = sol001
addIS.argument.do_int_stations      = True
addIS.argument.flags                = [h5parms,msin]

# apply the solutions
ndppp_applycal.control.type                    = dppp
ndppp_applycal.control.max_per_node            = {{ num_proc_per_node_limit }}
ndppp_applycal.control.error_tolerance         = {{ error_tolerance }}
ndppp_applycal.control.mapfiles_in              = [dpppconcat.output.mapfile,ddf_h5parms.output.mapfile]
ndppp_applycal.control.inputkeys                = [msins,parmdbs]
ndppp_applycal.control.inplace                 = True
ndppp_applycal.argument.numthreads             = {{ max_dppp_threads }}
ndppp_applycal.argument.msin                    = msins
ndppp_applycal.argument.msin.datacolumn        = DATA
ndppp_applycal.argument.msout.datacolumn       = {{ delaycal_col }}
ndppp_applycal.argument.msout.writefullresflag = False
ndppp_applycal.argument.msout.storagemanager   = dysco
ndppp_applycal.argument.steps                  = [applyddf]
ndppp_applycal.argument.applyddf.type           = applycal
ndppp_applycal.argument.applyddf.parmdb         = parmdbs
ndppp_applycal.argument.applyddf.correction     = fulljones
ndppp_applycal.argument.applyddf.solset         = sol001
ndppp_applycal.argument.applyddf.soltab         = [amplitude000,phase000]
```

removing `h5imp_ddf_map` and `h5imp_ddf` to instead apply each h5 to its corresponding MS. This assumes the mapfiles of dpppconcat and ddf_h5parms are sorted in the same way, I'm not 100% sure if ddf-pipeline guarantees this? They have almost identical names so I would think it may be safe, but it would be good if someone can confirm this.

**Comment by lmorabit** [comment]
the reason for merging in the first place is that we have run into issues with the formation of bands -- it doesn't necessarily match between prefactor, ddf-pipeline, and lofar-vlbi.  i think these cases are infrequent, and we've updated the createmap_target step to only process bands that exist in prefactor and ddf-pipeline solutions, so in theory that should take care of this problem ... but something this basic should also just work in losoto.

**Comment by tikk3r** [comment]
I think you're right they are infrequent cases and I see the pros for merging as well; it's a bit easier to lug around a single solution table instead of 24 and a little it's less bookkeeping. The cons I see is that it's a messy interpolation and you'll either lose the exact solutions if you just interpolate to the "fastest" spacing or end up with a huge h5parm if you interpolate to the "slowest" common spacing.

**Comment by lmorabit** [comment]
is this still an issue?

**Comment by tikk3r** [comment]
I think so? Circumventing the merge should work, but I'm not sure if the merging behaviour has been fixed.

**Comment by rvweeren** [comment]
Quick question, why are we not merging @tikk3r suggestion? (it is working and our current version is still doing the wrong thing (later we could think about a more optimized/cleaner fix))

**Comment by lmorabit** [comment]
Done. But now it will never get fixed in losoto since we've implemented a workaround!
