### ISSUE TITLE
No delay calibrator image produced

### ISSUE THREAD

**Issue by vijaymahatma** [lmorabit/long_baseline_pipeline#75]
After running the Delay-Calibration parset, the pipeline runs successfully, but fails to produce an image of the calibrator. In the directory after the pipeline has finished running, I have the files:

SL440512_L590163_SB244_uv_12A06A5EDt_121MHz_12A06A5F0t_144MHz.apply_delay_autoI.p.ps
SL440512_L590163_SB244_uv_12A06A5EDt_121MHz_12A06A5F0t_144MHz.apply_delay_autoI.ps
SL440512_L590163_SB244_uv_12A06A5EDt_121MHz_12A06A5F0t_144MHz.apply_delay_autoI_uvcut.ps

But SL440512_L590163_SB244_uv_12A06A5EDt_121MHz_12A06A5F0t_144MHz.apply_delay_autoI.ps is empty when opened. I attach below the diffmap log, showing clear errors in most steps of making the image. 
[SL440512_difmap.log](https://github.com/lmorabit/lofar-vlbi/files/6042939/SL440512_difmap.log)

**Comment by lmorabit** [comment]
@vmahat let me know if your test of the fix is successful.

**Comment by vijaymahatma** [comment]
> @vmahat let me know if your test of the fix is successful.

Yes, still waiting for Delay-Calibration to finish -- set it running last night

**Comment by lmorabit** [comment]
fixed with commit d8a3479be6ef211dc70b4117645eb2f850970477
