### ISSUE TITLE
circular to linear conversion is missing

### ISSUE THREAD

**Issue by rvweeren** [lmorabit/long_baseline_pipeline#79]
https://github.com/lmorabit/lofar-vlbi/blob/2f963246fe07e33b8f1b7b4d0b883b1abe466e42/Delay-Calibration.parset#L644

The delay selfcal script, current default settings in the pipeline (docircular=True), obtains solutions in circular correlations. That means the measurement sets need to be converted first to circular before this applycal can be run. Then after the applycal they need to be converted back to linear. (if docircular=False then this is not needed, so there also needs to be a switch for that)

**Comment by lmorabit** [comment]
Ah good catch!  What do you think is the best way to proceed? From what I recall it is best to find solutions in circular, but it can be quite inefficient to convert the data twice.  Hadn't we discussed at some point having a script that converted the solutions instead?  I think Jurjen was testing that at the last busy week.

**Comment by rvweeren** [comment]
>Ah good catch! What do you think is the best way to proceed? From what I recall it is best to find solutions in circular

I've come across cases where scalarphasediff does not make the images better (but also the other way around, so we need more tests here). A "temporary solution" would be to remove the --docircular from the selfcal command and also all the scalarphasediff entries in the solve. At least for now the applycal step in the parset is correct then. 

> Hadn't we discussed at some point having a script that converted the solutions instead?

Yes, [jurjen93](https://github.com/jurjen93) made progress with that but there was still an issue with a phase sign (if I remember correctly). BTW we still need to have a simple 'fulljones switch' in the applycal step if we have cconverted full jones solutions because the DP3 syntax is slightly different for fulljones applycal.

**Comment by lmorabit** [comment]
I think this is now closed with the updates to facetselfcal to generate linear solutions that can be applied to the data. All linear to circular and vice versa conversions should now be handled internally in lofar_facet_selfcal.
