### ISSUE TITLE
Plot positions of LBCS sources, image catalogue and potential target

### ISSUE THREAD

**Issue by jwpetley** [lmorabit/long_baseline_pipeline#85]
After the LBCS catalogue, LoTSS catalogue and image catalogue CSVs are produced, we could generate an inspection plot that shows the positions of the LBCS sources relative to the pointing centre. 

Optionally, one could provide an RA and DEC or a list of RAs and DECs as a parameter and have them plotted too. Perhaps with information on the distance between the pointing centre and the current "best choice" delay calibrator and the listed targets. At the moment the choice of delay-calibrator is made based on imaging the whole field (i.e looking for a compact source near to pointing centre). But for a particular target, it would be better to see positions relative to the target and pointing centre.  

I may make this script soon if I have the time but I thought I would open up an issue for now.

**Comment by lmorabit** [comment]
will be fixed in new CWL version of pipeline
